"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";import {Card} from "@/components/Card";import{PageHeader}from"@/components/PageHeader";import{Field,inputClass,buttonClass,Message,Empty}from"@/components/FormControls";import{supabase}from"@/lib/supabase";import type{Task,Project}from"@/lib/models";
const blank={title:"",description:"",priority:"Medium",status:"Active",due_date:"",project_id:""};
export default function TasksPage(){const[items,setItems]=useState<Task[]>([]),[projects,setProjects]=useState<Project[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[filter,setFilter]=useState("All"),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
async function load(){if(!supabase){setMessage("Supabase is not configured.");return}const[{data,error},{data:p}]=await Promise.all([supabase.from("tasks").select("*, project:projects(name)").order("created_at",{ascending:false}),supabase.from("projects").select("*").order("name")]);if(error)setMessage(error.message);else setItems(data??[]);setProjects(p??[]);setLoading(false)}useEffect(()=>{load()},[]);
async function save(e:FormEvent){e.preventDefault();if(!supabase||!form.title.trim())return;const payload={title:form.title.trim(),description:form.description.trim()||null,priority:form.priority,status:form.status,due_date:form.due_date||null,project_id:form.project_id?Number(form.project_id):null,completed:form.status==="Completed",updated_at:new Date().toISOString()};const x=editing?await supabase.from("tasks").update(payload).eq("id",editing):await supabase.from("tasks").insert(payload);if(x.error)setMessage(x.error.message);else{setEditing(null);setForm(blank);setMessage("Saved.");await load()}}
async function toggle(t:Task){if(!supabase)return;await supabase.from("tasks").update({completed:!t.completed,status:!t.completed?"Completed":"Active",updated_at:new Date().toISOString()}).eq("id",t.id);await load()}async function remove(id:number){if(!supabase||!confirm("Delete this task?"))return;await supabase.from("tasks").delete().eq("id",id);await load()}
function edit(t:Task){setEditing(t.id);setForm({title:t.title,description:t.description??"",priority:t.priority,status:t.status,due_date:t.due_date??"",project_id:t.project_id?String(t.project_id):""});window.scrollTo({top:0,behavior:"smooth"})}
const filtered=useMemo(()=>items.filter(t=>(filter==="All"||t.status===filter)&&`${t.title} ${t.description??""} ${t.project?.name??""}`.toLowerCase().includes(q.toLowerCase())),[items,q,filter]);
return <div><PageHeader title="Tasks" subtitle="Create, prioritize, schedule, and complete work across every project."/><Card title={editing?"Edit task":"New task"}><form onSubmit={save} className="grid gap-3 md:grid-cols-2"><Field label="Title"><input className={inputClass} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Project"><select className={inputClass} value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">General</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Description" className="md:col-span-2"><textarea className={inputClass} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Priority"><select className={inputClass} value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{["Low","Medium","High","Critical"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Status"><select className={inputClass} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{["Planning","Active","Paused","Completed"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Due date"><input type="date" className={inputClass} value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></Field><div className="flex items-end gap-2"><button className={buttonClass}>{editing?"Update":"Create"}</button>{editing&&<button type="button" className={buttonClass} onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div><Message text={message}/></form></Card><div className="my-4 grid gap-3 md:grid-cols-2"><input className={inputClass} placeholder="Search tasks…" value={q} onChange={e=>setQ(e.target.value)}/><select className={inputClass} value={filter} onChange={e=>setFilter(e.target.value)}>{["All","Planning","Active","Paused","Completed"].map(x=><option key={x}>{x}</option>)}</select></div>{loading?<Card>Loading…</Card>:filtered.length===0?<Empty>No tasks found.</Empty>:<div className="space-y-3">{filtered.map(t=><Card key={t.id}><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><button onClick={()=>toggle(t)} className={`text-left text-lg font-semibold ${t.completed?"line-through text-jarvis-muted":""}`}>{t.completed?"✓ ":"○ "}{t.title}</button><p className="text-sm text-jarvis-muted">{t.project?.name??"General"} · {t.priority}{t.due_date?` · due ${t.due_date}`:""}</p>{t.description&&<p className="mt-2 text-jarvis-muted">{t.description}</p>}</div><div className="flex gap-3 text-sm"><button onClick={()=>edit(t)} className="text-jarvis-glow">Edit</button><button onClick={()=>remove(t.id)} className="text-red-300">Delete</button></div></div></Card>)}</div>}</div>}
