-- Jarvis Home AI - Supabase schema
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  content text
);

alter table public.notes enable row level security;

-- MVP policy: publishable-key clients can read/write notes.
-- Before adding authentication or sensitive data, replace these with per-user policies.
create policy "MVP notes select" on public.notes for select to anon using (true);
create policy "MVP notes insert" on public.notes for insert to anon with check (true);
create policy "MVP notes delete" on public.notes for delete to anon using (true);
