"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Card } from "@/components/Card"; import { PageHeader } from "@/components/PageHeader";
import { Field,inputClass,buttonClass,Message,Empty } from "@/components/FormControls"; import { supabase } from "@/lib/supabase"; import type { Note } from "@/lib/models";
const blank={title:"",content:"",category:"General",tags:""};
export default function NotesPage(){const [items,setItems]=useState<Note[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
async function load(){if(!supabase){setMessage("Supabase is not configured.");setLoading(false);return} const {data,error}=await supabase.from("notes").select("*").order("updated_at",{ascending:false}); if(error)setMessage(error.message); else setItems(data??[]);setLoading(false)} useEffect(()=>{load()},[]);
async function save(e:FormEvent){e.preventDefault();if(!supabase||!form.title.trim())return;setMessage("Saving…");const payload={title:form.title.trim(),content:form.content.trim(),category:form.category.trim()||null,tags:form.tags.split(",").map(x=>x.trim()).filter(Boolean),updated_at:new Date().toISOString()}; const result=editing?await supabase.from("notes").update(payload).eq("id",editing):await supabase.from("notes").insert(payload); if(result.error)setMessage(result.error.message);else{setForm(blank);setEditing(null);setMessage("Saved.");await load()}}
function edit(n:Note){setEditing(n.id);setForm({title:n.title,content:n.content??"",category:n.category??"General",tags:(n.tags??[]).join(", ")});window.scrollTo({top:0,behavior:"smooth"})}
async function remove(id:number){if(!supabase||!confirm("Delete this note?"))return;const {error}=await supabase.from("notes").delete().eq("id",id);if(error)setMessage(error.message);else await load()}
const filtered=useMemo(()=>items.filter(n=>`${n.title} ${n.content??""} ${(n.tags??[]).join(" ")}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
return <div><PageHeader title="Notes" subtitle="Persistent Jarvis memory stored in Supabase."/><Card title={editing?"Edit note":"Capture a note"}><form onSubmit={save} className="grid gap-3 md:grid-cols-2"><Field label="Title"><input className={inputClass} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Category"><input className={inputClass} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field label="Content" className="md:col-span-2"><textarea rows={5} className={inputClass} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></Field><Field label="Tags, comma separated" className="md:col-span-2"><input className={inputClass} value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></Field><div className="flex gap-2"><button className={buttonClass}>{editing?"Update":"Save"}</button>{editing&&<button type="button" className={buttonClass} onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div><Message text={message}/></form></Card><div className="my-4"><input className={inputClass} placeholder="Search notes…" value={q} onChange={e=>setQ(e.target.value)}/></div>{loading?<Card>Loading…</Card>:filtered.length===0?<Empty>No notes found.</Empty>:<div className="grid gap-4 md:grid-cols-2">{filtered.map(n=><Card key={n.id} title={n.title} eyebrow={n.category??"Note"}><p className="whitespace-pre-wrap text-jarvis-muted">{n.content}</p><div className="mt-3 flex flex-wrap gap-2">{(n.tags??[]).map(t=><span key={t} className="rounded-full border border-jarvis-line px-2 py-1 text-xs">{t}</span>)}</div><div className="mt-4 flex gap-3 text-sm"><button onClick={()=>edit(n)} className="text-jarvis-glow">Edit</button><button onClick={()=>remove(n.id)} className="text-red-300">Delete</button></div></Card>)}</div>}</div>}
